import type { Metadata } from "next";
import { Rubik } from 'next/font/google'
import "./lib/globals.css";

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik'
})

export const metadata: Metadata = {
  title: "Riley Pankow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.className}>
      <body className="bg-gray-100 m-auto w-full lg:w-275">
        {children}
      </body>
    </html>
  );
}
